### PR TITLE
New controller plugin, computeAlteredInputs

### PR DESCRIPTION
**Pull request by grizzm0**
Playing around with the idea of only validating altered fields to stop unique validators from going off if the field wasn't changed (email validator for example).

Thoughts? @bakura10 

```php
/**
 * @param array $params
 *
 * @return ResourceViewModel
 * @throws NotFoundException
 */
public function put(array $params)
{
    $id = (int)$params['id'];

    /** @var $user UserInterface */
    if (!$user = $this->userRepository->findOneBy(['id' => $id])) {
        throw new NotFoundException();
    }

    $validationGroup = $this->computeAlteredInputs(UserInputFilterInterface::class, $user);

    // Only validate and update if we got altered fields
    if (!empty($validationGroup)) {
        $data = $this->validateIncomingData(UserInputFilterInterface::class, $validationGroup);
        $user = $this->hydrateObject(ClassMethods::class, $user, $data);

        $user = $this->userService->update($user);
    }

    return new ResourceViewModel(['user' => $user], ['template' => 'mostad/user']);
}
```

### CODE REVIEW

**Comment by bakura10** [comment]
I don't really like this. I've indeed face the same thing for user class, but I think this is the wrong solution to the problem.

For now, what I've done is creating two different input filters. This feel cleaner.

What we need actually is having smarter input filters (this is something I will do for ZF3). It would be nice if we could create named validation groups inside the input filter:

```php
$this->add([
    'name' => 'email',
    'group' => 'register',
    'validators' => [] // Add the specific validator for register group
]);

$this->add([
    'name' => 'email',
    'group' => 'update',
    'validators' => [] // Add the specific validator for register group
]);
```

Then you could validate the input filter against a name validation group (the runAgainst method is based on the initial refactoring):

```php
$inputFilter->runAgainst($data, 'register');
```

Then ZfrRrest could use that. I think this is a much better approach.

**Comment by grizzm0** [comment]
That doesn't really solve the problem. You'd still have to validate the email if it gets changed.
The only solution I see is something similar to this or a smarter validator that doesn't fail if item being updated already owns the unique field.

**Comment by bakura10** [comment]
I've checked my code and actually I use only one InputFilter, but override the isValid to delete the "NoObjectExists" vlaidator on email (for registrtaion) to a "UniqueObject" validator (for update). This is a bit verbose and we would benefit graetly from having named validation group right into input filter, but for now that does the trick.

```php
/**
 * Validate and filter the data of a user
 *
 * @author  Michaël Gallego <mic.gallego@gmail.com>
 * @licence MIT
 */
class UserInputFilter extends InputFilter
{
    /**
     * @var EntityManagerInterface
     */
    private $entityManager;

    /**
     * @param EntityManagerInterface $entityManager
     */
    public function __construct(EntityManagerInterface $entityManager)
    {
        $this->entityManager = $entityManager;

        $this->add([
            'name'       => 'email',
            'required'   => true,
            'validators' => [
                [
                    'name'    => EmailAddress::class,
                    'options' => [
                        'messages' => [
                            EmailAddress::INVALID_FORMAT => 'Email address is invalid'
                        ]
                    ]
                ],
                [
                    'name'    => StringLength::class,
                    'options' => ['max' => 255]
                ],
                [
                    'name'    => NoObjectExists::class,
                    'options' => [
                        'object_repository' => $entityManager->getRepository(User::class),
                        'fields'            => ['email'],
                        'messages'          => [
                            NoObjectExists::ERROR_OBJECT_FOUND => 'User with this email address already exists'
                        ]
                    ]
                ]
            ],
            'filters' => [
                ['name' => StringTrim::class],
                ['name' => StringToLower::class]
            ]
        ]);
    }

    /**
     * @param  mixed $context
     * @return bool
     */
    public function isValid($context = null)
    {
        // If the context is an object, we do additional things as this is an update
        if ($context instanceof User) {
            $this->data['id'] = $context->getId();
            $this->prepareInputFilterForUpdate($context);
        }

        return parent::isValid($context); // TODO: Change the autogenerated stub
    }

    /**
     * @param User $user
     */
    private function prepareInputFilterForUpdate(User $user)
    {
        // For the email, we need to copy all the existing validators, but remove the "NoObjectExists" to replace
        // it by a "UniqueObject" filter

        /** @var \Zend\InputFilter\InputInterface $emailInput */
        $emailInput     = $this->inputs['email'];
        $validatorChain = $emailInput->getValidatorChain();

        $newValidatorChain = new ValidatorChain();

        foreach ($validatorChain->getValidators() as $validator) {
            $instance = $validator['instance'];

            if ($instance instanceof NoObjectExists) {
                continue;
            }

            $newValidatorChain->attach($instance);
        }

        // Finally, attach the new one
        $newValidatorChain->attachByName(UniqueObject::class, [
            'object_repository' => $this->entityManager->getRepository(User::class),
            'object_manager'    => $this->entityManager,
            'use_context'       => true,
            'fields'            => ['email'],
            'messages'          => [
                UniqueObject::ERROR_OBJECT_NOT_UNIQUE => 'User with this email address already exists'
            ]
        ]);

        $emailInput->setValidatorChain($newValidatorChain);
    }
}
```


The thing is that for thsi to work, you need to pass the context to the input filter. ZfrRest supports that with the third, optional parameter to validateIncomingData. Here is my update method, for instance:

```php
public function put(array $params)
    {
        if (!($user = $this->userService->getById($params['user_id']))) {
            throw new NotFoundException();
        }

        if (!$this->isGranted('user.update', $user)) {
            throw new UnauthorizedException();
        }

        $data = $this->validateIncomingData(UserInputFilter::class, [], $user);
        $this->hydrateObject(UserHydrator::class, $user, $data);

        $this->userService->update($user);

        $projects = $this->projectService->getByUser($user);

        return new ResourceViewModel(['user' => $user, 'projects' => $projects], ['template' => 'users/user']);
    }
```

**Comment by grizzm0** [comment]
Hum, ok. Was actually playing around with the UniqueObject validator before trying this approach. Couldn't get it working. :p But I'll look at it again I guess.

**Comment by bakura10** [comment]
Yeah, the trick is working with the context. The UniqueObject validator is far from ideal from a usage point of view :).

**Comment by grizzm0** [comment]
Closing after this discussion. ;]

**Pull request closed without merging**
