### PR TITLE
Fixing bug #206

### PR DESCRIPTION
**Pull request by hopsey**
Composer will now accept 
- zend-mvc
- zend-servicemanager
- zendframework
  versioned as ^3.0

### CODE REVIEW

**Comment by bakura10** [comment]
Tests are not passing :(.

**Comment by hopsey** [comment]
Fixing some errors would require migrating to 3.0 with no backward compatibility :( shall we go with it?

**Comment by bakura10** [comment]
Tests are still failing.

A lot of modules (especially Apigility) have managed to support both 2.x and 3.x branch. You should check how they did it.

Sorry for not being able to provide more help, but I really don't have time to support this module anymore and I don't use it anymore :(.

**Comment by hopsey** [comment]
I don't have time for now either, I'll just leave it as it is and perhaps come back some other time.

**Pull request closed without merging**
